---
# tasks file for lsdyna  

- name: make lsdyna directory
  become: true
  file:
    path: "/nfs/scratch/lsdyna/install"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes

#Install LSDYNA
- name: download lsdyna binaries
  get_url:
    url: "{{lsdyna_binaries}}"
    dest: "/nfs/scratch/lsdyna/install"
    mode: 0777

- name: untar lsdyna binaries
  ansible.builtin.unarchive:
    src: "{{ item }}" 
    dest: "/nfs/scratch/lsdyna/install" 
  with_fileglob:
    - "/nfs/scratch/lsdyna/install/*"

# Post Installation 

- name: make models directory
  become: true
  file:
    path: "/nfs/scratch/lsdyna/models"
    state: directory
    owner: opc
    mode: 0770
    group: opc
    recurse: yes

- name: download model 
  get_url: 
    url: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/5f6Rh-GE-QHuFLH2DpVNIQHoCRjZdX3avoHMZjFxN7BarASvQSMmMZ4-iGPTV2e1/n/hpc/b/HPC_BENCHMARKS/o/3cars_shell2_150ms_rev02.tar" 
    dest: "/nfs/scratch/lsdyna/models"

- name: untar model
  ansible.builtin.unarchive:  
    src: "{{ item }}" 
    dest: "/nfs/scratch/lsdyna/models" 
  with_fileglob:
    - "/nfs/scratch/lsdyna/models/*"









